.\" Manpage template for SWARM
.TH bar 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBbar\fP - Shows a progress in different ways

.SH SYNOPSYS
bar  [ options ]  [ MESSAGE ]

.SH DESCRIPTION
This function is a simple way to let users know that something is beeing worked on.
.RE
In its simplest call, it will print a dash, that rotates upon each new call.
.RE
If you pass cur and max values, it will change to a \fB[ cur / max ]\fP output style,
unless you pass \fB-b\fP which will finaly enable the progress bar output.


.SH OPTIONS
  -b			Show progress bar
  -B '#'	Change the 'bar-symbol' provided by the theme
  -c VALUE	Sets the current value to VALUE
  -m VALUE	Sets the maximum value to VALUE

  -C			Clears the line -> Removes content that was previously written on the same line.
  -i VALUE	Sets this (of multiple) invocations of bar to index:VALUE, only required for \fB-B dash\fP or if \fB-B NUM\fP is not used with \fB-m NUM\fP.
  -p			Show calculated percentage
  -r			Reset


.SH EXAMPLE
  bar "Working on this task..."
.RE
  bar -b -m 100 -c 50 "Got the half of this task!"
.RE


.SH PLANNED - LOW PRIO
  --color [ green[70]orange[80] red ] Colorize the progressbar as indicated.
.PP
If \fB--color\fP is used without additional arguments, by default it will color everything lower than 70% in green, everything that is lower than 80 in orange and everything above in red.
.PP
  bar -b --color white50,green75,red -c 51 -m 100 "Colored bar!"
.RE

.SH SEE ALSO
\fBbash\fP(1), \fBprintl\fP(1), \fBdd\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
