.\" Manpage template for SWARM
.TH download 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBdownload\fP - Download files from web

.SH SYNOPSYS
download [\fB-r\fP] [-f|--full] [-d|--dir /path/to/dir] [\fB-o [/path/to/]FILE1 \fP] URL1 [URL2 ..]

.SH OPTIONS
.TP
.B
\fB-f|--full\fP
Shows full path when file exists or download is complete.
.TP
.B
\fB-d DIRECTORY\fP
Save all passed URLs to DIRECTORY.
.TP
.B
\fB-o FILE\fP
Saves mandatory URL1 as FILE, if you just download a single file, you can pass /path/to/file as well.

Saves every further URL2..999 with swarm.str.genfilename FILE, which is the reason you should use the [\vB-d DIRECTORY[\vP option for downloading multiple files.

.SH EXAMPLE
download https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.2.1.tar.xz

.SH SEE ALSO
\fBbash\fP(1), \fBcurl\fP(1), \fBwget\fP(1), \fBdownload\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM/issues\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
