.\" Manpage template for SWARM
.TH header 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
header - Prints borders and colors the full line

.SH SYNOPSYS
header [--default] [[str1] [str2] [str3]]

.SH DESCRIPTION
Prints one string on the left

Prints two strings, left and right

Prints three strings: left, centered and right


.SH OPTIONS
.TP 5
.B
--default
Shows either one of:
.TP 5
 	*	\fbSWARM <VERSION>-<BUILD> (<DISTRO>)\fP
.TP 5
	*	\fb$script_name $script_version (<DISTRO>)\fP
.TP 5
On the left side, and on the right side, always:
.TP 5
	[ARGS] | DATE/TIME


.SH EXAMPLE
header "My scriptname" "Some other info"
.TP
header --default "${@}"

.SH SEE ALSO
\fBbash\fP(1), \fBprintl\fP(1), \fBprinte\fP(1), \fBswarm.print.border\fP(1), \fBswarm.print.text\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM/issues\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
