.\" Manpage template for SWARM
.TH printe 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
printe - Display up to three strings per line, ending with a NL

.SH SYNOPSYS
printe [-c] [-N] [-1|-2|-3] [-|--] [str1 [str2 [str3]]]

.SH DESCRIPTION
This is the function that should be used the most to display any data to endusers. By default it accepts up to 3 strings per output line, this can be changed via options. To use the center, you must provide 3 strings.
.RE
* Prints one string on the left
.RE
* Prints two strings left and right
.RE
* Prints three strings left, centered and right

.SH OPTIONS
.TP
-c			Clears the line before printing
.TP
-N			No Newline at the end of line
.TP
-1			Force left aligned text only
.TP
-2			Force left & right aligned text only
.TP
--left		Default behaviour if only STRING1 (left) is pased.
		This will make the cursor stay on line (\fB-N\fP).
.TP
--center  	Prints STRING1 (left) in the center of the line.
		This will make the cursor stay on line (\fB-N\fP).
.TP
--right		Prints STRING1 (left) on the right side.
		This will make the cursor stay on line (\fB-N\fP).
.TP
-|--			Recieve strings from pipe

.SH EXAMPLE
.P
printe "Hello World"
.P
printe "left" "right"
.P
printe "left side" "in the center" "on the right side"
.P
printe --center "center string"
.RE
printe -c --right "right string"
.P
grep PATTERN FILE | printe -2 --
.P
sudo fdisk /dev/sda -l | printe -1 --


.SH SEE ALSO
\fBbash\fP(1), \fBswarm.print.border\fP(1), \fBswarm.print.text\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM/issues\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
