.\" Manpage template for SWARM
.TH swarm.str.hash 1 "Copyleft 1995-2021" "SWARM 1.0 "SWARM Manual"

.SH NAME
\fBswarm.str.hash \fP- Prints the hash value of passed item
\fB
.SH SYNOPSYS
swarm.str.hash [\fB-h\fP|\fB--help\fP] [\fB-t|--type short,names,..\fP] STRING1 FILE2 DIR3 ...
.SH DESCRIPTION
Returns hash codes of specified type (default md5) in a visual manner.
.B

.SH OPTIONS
.TP
.B
.TP
.B
\fB-t|--type\fP TYPE
Pass which type of hashing you want, default/fallback: md5sum
.PP
Hash types supported: sha1sum, sha224sum, sha256sum, sha384sum, sha512sum
.SH EXAMPLE

swarm.str.hash \fB-t\fP 384 "some string"
.PP
cat file.txt | swarm.str.hash -
.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM\fP
.PP
.SH AUTHOR
Simon Arjuna Erat, Switzerland
.PP
.SH LICENSE
GNU Public License V2
