.\" Manpage template for SWARM
.TH swarm.str.bool2str 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
bool2str - Converts a bool value to text

.SH SYNOPSYS
\fBswarm.str.bool2str\fP [-c -C -d -t -y] $?

.SH OPTIONS
.TP
\fB-c\fP
	Makes first letter Capital
.TP
\fB-C\fP
	Makes all letters CAPITAL
.TP
\fB-d\fP
	Returns: done / fail
.TP
\fB-s\fP
	Returns: success / failure
.TP
\fB-t\fP
	Returns: true / false
.TP
\fB-y\fP
	Returns: yes / no

.SH EXAMPLE
yesno "Do you like this?"
.RE
answer="$(swarm.str.bool2str -y $?)"

.SH SEE ALSO
\fBbash\fP(1), \fByesno\fP(1), \fBstatus\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM/issues\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
