.\" Manpage template for SWARM
.TH swarm.util.cp 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBswarm.util.cp\fP - Copy, SWARM-style

.SH SYNOPSYS
swarm.util.cp [-d -f -l -q] SOURCE1 [..] TARGET

.SH DESCRIPTION
\fBswarm.util.cp\fP verifies each \fBSOURCE\fP vs any existing \fBTARGET\vP checksum, if multiple \fBSOURCES\fP are passed, it expects \fBTARGET\fP to be a directory, if it does not exists, it will create it first.

.SH ENVIRONMENT
.TP
\fB$CP\fP
You can use this variable as a shorthand for \fBswarm.util.cp\fP if you prefer.
.TP
\fB$CP_EXEC\fP
If you write scripts that are supposed to run on multiple plattforms, it is recomended that you use this over the 'plain command' cp if you do not want to use \fBswarm.util.cp\fP, as this variable will refer to the found file on the local machine or - where available - to the builtin variant.

.SH OPTIONS
.TP
\fB--dash\fP
Switch to (animated) dash-mode
.TP
\fB--line\fP
Print all items on one line.
.TP
\fB--long\fP
Show long names (full passed target path)

.SH EXAMPLE
swarm.util.cp * /path/to/destination[/file]
.RE
swarm.util.cp \fB--long\fP * /path/to/destination[/file]
.RE
swarm.util.cp \fB--dash\fP \fB--line\fP * /path/to/destination[/file]

.SH SEE ALSO
\fBbar\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM/issues\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
