.\" Manpage template for SWARM
.TH swarm.util.cd 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBswarm.util.cd\fP - Change Directory, the save way

.SH SYNOPSIS
.TP
\fBswarm.util.cd\fP DIRECTORY

.SH ENVIRONMENT
.TP
\fB$CD\fP
You can use this variable as a shorthand for \fBswarm.util.cd\fP if you prefer.
.TP
\fB$CD_EXEC\fP
If you write scripts that are supposed to run on multiple plattforms, it is recomended that you use this over the 'plain command' cd if you do not want to use \fBswarm.util.mkdir\fP, as this variable will refer to the found file on the local machine or - where available - to the builtin variant.

.SH DESCRIPTION
\fBswarm.util.cd\fP will attempt to change to passed DIRECTORY
.PP
It will check wether passed DIRECTORY exists or not. If it does it will change and exit successfully.
If it does not exist, it will ask the user if it should create it.

.SH OPTIONS
.TP
\fB-v\fP
Will enable verbose mode.
.PP
This will enable a simple status message per passed item.

.SH EXAMPLE
.PP
    swarm.util.cd "$HOME" || exit 1

.PP
    no | swarm.util.cd "../wrong/..sub/dir"

.SH SEE ALSO
\fBswarm.util.mkdir\fP(1)

.SH BUGS
     Report bugs to: https://github.com/sri-arjuna/SWARM/issues
     SWARM - Homepage: https://github.com/sri-arjuna/SWARM/
     General help using GNU software: <http://www.gnu.org/gethelp/>

.SH AUTHOR
This manpage and the function swarm.util.cd was written by Simon Arjuna Erat (sea) for SWARM version 1.0
