.\" Manpage template for SWARM
.TH SWARM 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBtui-wait\fP - Wait some time

.SH SYNOPSYS
wait [ -v ] TIME [ "Message to user" ]

.SH OPTIONS
  -v		Verbose ; Prints each second on its own line

.SH EXAMPLE
wait -v 1m "Wait a minute"
.RE
wait 1h "Wait an hour"

.SH SEE ALSO
\fBbash\fP(1), \fBprintl\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
