.TH SWARM-colors 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBColors\fP - How to use

.SH DESCRIPTION
SWARM contains 2 sets of code variables, one full and one short variant. The full variant obviously starts with \fBSWARM_\fP and then either \fBFONT_\fP or \fBCOLOR_\fP before defining wether its \fBFG_\fP (Fore Ground) or \fBBG_\fP (Back Ground) to finaly name the color.
.RE
The short variant starts with either \fBc_\fP, \fBcf_\fP for char foregrond or \fBcb_\fP for char background.
.RE
Likewise would the fonts in the short variant be called like: \fBfnt_\fP,
.RE
 
.RE
After any font change, be sure to 'close' the 'tag' with either \vB\\$SWARM_COLOR_RESET\vP or \vB\\$c_reset\vP.


.SH TERMINAL DEFAULTS
	SWARM_RESET			"\\033[0m"
.RE
	SWARM_COLOR_RESET		"\\033[0m"
.RE
	SWARM_COLOR_INVERT		"\\033[7m"
.RE
	SWARM_COLOR_CLEARLINE	"\\033[2k"
.RE

.SH FONT MODES
	SWARM_FONT_BOLD		"\\033[1m"
.RE
	SWARM_FONT_STROKE		"\\033[9m"
.RE
	SWARM_FONT_UNDERLINE	"\\033[4m"
.RE
	SWARM_FONT_BLINK		"\\033[5m"
.RE

.SH COLOR FOREGROUND
	SWARM_COLOR_FG_BLACK	"\\033[30m"
.RE
	SWARM_COLOR_FG_WHITE	"\\033[37m"
.RE
	SWARM_COLOR_FG_GREEN	"\\033[32m"
.RE
	SWARM_COLOR_FG_CYAN		"\\033[36m"
.RE
	SWARM_COLOR_FG_RED		"\\033[31m"
.RE
	SWARM_COLOR_FG_BLUE		"\\033[34m"
.RE
	SWARM_COLOR_FG_YELLOW	"\\033[33m"
.RE
	SWARM_COLOR_FG_PURPLE	"\\033[35m"
.RE
	SWARM_COLOR_FG_GREY		"\\033[38m"
.RE

.SH COLOR FOREGROUND
	SWARM_COLOR_BG_BLACK	"\\033[40m"
.RE
	SWARM_COLOR_BG_WHITE	"\\033[47m"
.RE
	SWARM_COLOR_BG_GREEN	"\\033[42m"
.RE
	SWARM_COLOR_BG_CYAN		"\\033[46m"
.RE
	SWARM_COLOR_BG_RED		"\\033[41m"
.RE
	SWARM_COLOR_BG_BLUE		"\\033[44m"
.RE
	SWARM_COLOR_BG_YELLOW	"\\033[43m"
.RE
	SWARM_COLOR_BG_PURPLE	"\\033[45m"
.RE
	SWARM_COLOR_BG_GREY		"\\033[48m"
.RE



.SH TERMINAL DEFAULTS (short)
	c_invert		"$SWARM_COLOR_INVERT"
.RE
	c_reset		"$SWARM_COLOR_RESET"
.RE
	c_clear		"$SWARM_COLOR_CLEARLINE"
.RE
	
.SH FONT MODES (short)
For the font modes, it is recomended to use the according function.
.RE
For bold, this would be: \fBswarm.print.bold "Your message"\fP
.RE

	fnt_bold		"$SWARM_FONT_BOLD"
.RE
	fnt_stroke	"$SWARM_FONT_STROKE"
.RE
	fnt_underline	"$SWARM_FONT_UNDERLINE"
.RE
	fnt_blink		"$SWARM_FONT_BLINK"
.RE
	
.SH COLOR BACKGROUND (short)
	cb_black		"$SWARM_COLOR_BG_BLACK"
.RE
	cb_blue		"$SWARM_COLOR_BG_BLUE"
.RE
	cb_cyan		"$SWARM_COLOR_BG_CYAN"
.RE
	cb_green		"$SWARM_COLOR_BG_GREEN"
.RE
	cb_grey		"$SWARM_COLOR_BG_GREY"
.RE
	cb_purple		"$SWARM_COLOR_BG_PURPLE"
.RE
	cb_red		"$SWARM_COLOR_BG_RED"
.RE
	cb_white		"$SWARM_COLOR_BG_WHITE"
.RE
	
.SH COLOR FOREGROUND (short)
	cf_black		"$SWARM_COLOR_FG_BLACK"
.RE
	cf_blue		"$SWARM_COLOR_FG_BLUE"
.RE
	cf_cyan		"$SWARM_COLOR_FG_CYAN"
.RE
	cf_green		"$SWARM_COLOR_BG_GREEN"
.RE
	cf_grey		"$SWARM_COLOR_FG_GREY"
.RE
	cf_purple		"$SWARM_COLOR_FG_PURPLE"
.RE
	cf_red		"$SWARM_COLOR_FG_RED"
.RE
	cf_white		"$SWARM_COLOR_FG_WHITE"
.RE



.SH EXAMPLE
beispiel

.SH SEE ALSO
\fBbash\fP(1), \fBswarm\fP(1), \fBconsole_codes\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
