.TH SWARM-edit 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBedit\fP - Opens passed files in the favorite editor (gui/cli)

.SH SYNOPSYS
edit [ -c ] [/path/to/]FILE [../]FILE2 \.\.\.

.SH DESCRIPTION
Opens provided FILE/s in the preferred editor according to environment. In multi-user or emergency stage it will open \"$EDITOR_CLI\" and in graphical stage it will open \"$EDITOR_GUI\".

.SH OPTIONS
  -c		Force CLI application

.SH SEE ALSO
\fBbash\fP(1), \fBprinte\fP(1), \fBpick\fP(1), \fBcfg.set\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
