.TH SWARM 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBpress\fP - The classic one

.SH SYNOPSYS
press [-c -l -r] [STRING]

.SH DESCRIPTION
"Press [ENTER] to continue" is default text, which is is printed left and right. The text can be changed by passing a different STRING.

.SH OPTIONS
 -c	Prints one center aligned text.
 -l	Prints the text only on the left side.
 -r	Prints the text only on the right side.

.SH EXAMPLES
press
.RE
press -c


.SH SEE ALSO
\fBbash\fP(1), \fBread\fP(1), \fBprintl\fP(1), \fBswarm.print.border\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/swarm\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
