.\" Manpage template for SWARM
.TH printfile 1 "Copyleft 1995-2021" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBprintfile \fP- Print a file to screen and wrap SWARM borders around it
\fB
.SH SYNOPSYS
printfile [\fB-d\fP DELAY] [\fB-tT\fP] FILE "Some String" \.\.\.
.SH OPTIONS
.TP
.B
\fB-d\fP DELAY
Waits DELAY seconds before it prints the next char.
DELAY may be an integer or flaoting point like "0.007"
This also triggers the typewriter "\fB-t\fP"
.TP
.B
\fB-t\fP
Enables typewriter mode, using default delay of 0.05
.TP
.B
\fB-T\fP
Prints the file name with title before it prints its content
.SH EXAMPLE

printfile file.txt
.PP
printfile \fB-T\fP /path/to/multiple/files*
.PP
printfile \fB-t\fP "Hello $USER, how are you today?"
.SH HINTS
In typewriter mode you can pass a mixed list of files and strings.

.SH SEE ALSO
\fBbash\fP(1), \fBcat\fP(1), \fBread\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
