.TH SWARM-printl 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBprintl \fP- Display up to three strings on the current line and do not print NL.
\fB
.SH SYNOPSYS
printl [ -1 -2 -- ] [str1 [str2 [str3]]]

.SH DESCRIPTION
This function can be used to keep changing the text of the current line. A good use-example for this would be the \fBprogress\fP-function. Allthough you can pipe a data stream to \fBprintl\fP it will print each output on its own line - using \fBprinte\fP.
.RE
* Prints one string on the left
.RE
* Prints two strings, left and right
.RE
* Prints three strings: left, centered and right

.SH OPTIONS
  -1		Forces to use only left output
  -2		Forces to use left and right output only
  --		Reads from pipe, this will use \fBprinte\fP

.SH EXAMPLE
printl "Replace me"
.RE
printl "Replaced previous line"
.RE
printl "Replaced again"
.PP
grep PATTERN FILE | printl -2 --


.SH SEE ALSO
\fBbash\fP(1),
.SH SEE ALSO
\fBbash\fP(1), \fBconsole_codes\fP(4), \fBgawk\fP(1), \fBgrep\fP(1), \fBprintf\fP(1), \fBprogress\fP(1), \fBprinte\fP(1), \fBswarm.print.border\fP(1), \fBswarm.print.text\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/swarm\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
