.TH SWARM 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBlist\fP - List items, with diffrent flavours of indexing

.SH SYNOPSYS
list [ -0 -1 -2 -a -n -r ] $LIST or "${ARRAY[@]}"

.SH DESCRIPTION
This prints a passed list with a leading numbrered index. This can be changed to roman letters, alphabetic ordering.

.SH OPTIONS
  -a		Use letters instead of numbers
  -r		Use roman letters instead of numbers (up to 3000 valid)
  -n		Use regular numbers for counting
  -0		Print a menu entry "Back" as index 0
  -1 | -2	Force to use 1 or 2 rows (left, left & right) instead of 3 (default)

.SH EXAMPLE
  printlist -n $LIST
.PP
  printlist -2 -r "${ARRAY[@]}"
.PP
  printlist -0 $LIST

.SH SEE ALSO
\fBbash\fP(1), \fBprinte\fP(1), \fBswarm.str.num2roman\fP(1), \fBswarm.str.num2alpha\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/swarm\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
