.TH SWARM-rnd 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBrnd \fP- Prints a random number within range (default: 0-100)

.SH SYNOPSYS
rnd [ -p COUNT VALUE ] [ -l COUNT ] [MAXVAL] | [MINVAL MAXVAL]

.SH OPTIONS
  -p COUNT VALUE 	Prints COUNT permutations of VALUE
  -l COUNT		Prints COUNT random numbers

.SH EXAMPLE
rnd
.RE
rnd -p 4 150
.RE
rnd -l 5 300 600

.SH SEE ALSO
\fBbash\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
