.TH SWARM 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBrnd \fP- Prints a random number within range

.SH SYNOPSYS
rnd [ -p|--perm COUNT -l COUNT ] [MAXVAL] | [MINVAL MAXVAL]

.SH OPTIONS


.SH EXAMPLE
rnd
.RE
rnd -p 4 150
.RE
rnd 300 320

.SH SEE ALSO
\fBbash\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/swarm\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
