.TH SWARM 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBswarm.print.text\fP - Prints the text for default output

.SH SYNOPSYS
swarm.print.text [ -h -t ] [str1] [str2] [str3]

.SH DESCRIPTION
This function is one of the core visuals and is supposed for internal use only.
.PP
It is used by every other function that has any kind of themed output.

.SH OPTIONS
  -t		\fBTitle\fP
  		Prints blue border and uses white background for the line.

  -h		\fBHeader\fP
  		Prints border all of the fline line blue,

.SH EXAMPLE
swarm.print.border -h
.RE
swarm.print.border -t
.RE
swarm.print.border

.SH SEE ALSO
\fBbash\fP(1), \fBconsole_codes\fP(4), \fBgawk\fP(1), \fBgrep\fP(1), \fBprintf\fP(1), \fBprinte\fP(1), \fBswarm.print.border\fP(1), \fBswarm.print.text\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/swarm\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
