.\" Manpage template for SWARM
.TH swarm.util.isGUI 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBswarm.util.isGUI\fP- Returns true (0) if user is in GUI

.SH SYNOPSYS
$isGUI


.SH EXAMPLE
.RE
    if $isGUI
.RE
    then
.RE
         zenity \fB--info\fP \fB--text\fP="You are in GUI!"
.RE
    else
.RE
        printl \fB-E\fP "Your terminal say it is: \044(tui-bol-gui \fB-v\fP)"
.RE
    fi

.SH ENVIRONMENT
.TP
.B
XDG_CURRENT_DESKTOP
Will return the Desktop Environment name on an X11 session
.TP
.B
DESKTOP_SESSION
Will return the Desktop Environment name on any other session

.SH SEE ALSO
\fBbash\fP(1)
.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
