.TH SWARM-util.isRoot 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBswarm.util.isRoot \fP- Returns true if user is root

.SH SYNOPSYS
$isRoot

.SH EXAMPLE
  $isRoot && \\
.RE
		$GREP $USER /etc/passwd || \\
.RE
		status 1 "No Access"

.SH SEE ALSO
\fBbash\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
