.TH swarm-str.extension 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBswarm.str.extension\fP - Get the extension of the file, if any

.SH SYNOPSYS
tui-str-extension "File with spaces.some string.txt"

.SH EXAMPLE
swarm.str.extension /etc/tui/tui.conf
.PP
swarm.str.extension /etc/ld.so.cache

.SH SEE ALSO
\fBbash\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
