.TH SWARM 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBswarm.str.usb\fP - Select an USB storage and print its adress (/dev/??)

.SH SYNOPSYS
swarm.str.usb [ -a ]

.SH OPTIONS
  -a		Auto select entry if only one was found

.SH EXAMPLE
usb=$(swarm.str.usb)
.RE
usb=$(swarm.str.usb -a)

.SH SEE ALSO
\fBbash\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/swarm\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
