.TH SWARM 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
bool2str - Converts a bool value to text

.SH SYNOPSYS
\fBswarm.str.bool2str\fP [-c -C -d -t -y] $?

.SH OPTIONS
  -c		Makes first letter Capital
  -C		Makes all letters CAPITAL
  -d		Returns: done/fail
  -t		Returns: true/false
  -y		Returns: yes/no

.SH EXAMPLE
yesno "Do you like this?"
.RE
answer="$(swarm.str.bool2str -y $?)"

.SH SEE ALSO
\fBbash\fP(1), \fByesno\fP(1), \fBstatus\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/swarm\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
