.TH SWARM-terminals 1 "Copyleft 1995-2020" "SWARM 1.0" "SWARM Manual"

.SH NAME
\fBtui-terminal\fP - Executed commands in a new terminal

.SH SYNOPSYS
tui-terminal [ ] "echo \$USER" | "[ condition ] && action"

.SH DESCRIPTION
Opens provided command or file in the preferred terminal window.

.SH OPTIONS


.SH SEE ALSO
\fBbash\fP(1), \fBpick\fP(1), \fBprintlist\fP(1), \fBtitle\fP(1), \fBprinte\fP(1)

.SH BUGS
Report bugs on: \fBhttp://github.com/sri-arjuna/SWARM\fP

.SH AUTHOR
Simon Arjuna Erat, Switzerland

.SH LICENSE
GNU Public License V2
