#!/usr/bin/env bash
$CAT<<-EO_SCREEN
#!/usr/bin/env bash
#--------------------------------
# Your LICENSE information
# Other descriptions
#
#--------------------------------
# This script requires SWARM (Shell Wrapper And Runtime Modifier)
# If this script is not displayed properly,
# make sure that the directory SWARM is at ./SWARM relative to this file.
#--------------------------------
#
# Script Information
#
	script_license="GPLv2"		# This is only a suggestion
	script_version=0.1		# This variable is also used by 'header --default'
	ME=\${0##*/}			# An easy way to refer to the filename
	ME_DIR=\${0/\$ME}		# Or the dir of the script
	script_name=\${ME/.sh}		# aka Pretty Name, dynamic approach
#
# Load SWARM
#
	# For more information, please see (execute): ./SWARM/runtime
	{ cd "\$ME_DIR" ; source SWARM/runtime ; cd "\$OLDPWD" ; }
#
# Variables
#
	define -i i=0				# Defines an integer variable '\$i'
	define -a REQ_CMD="" REQ_MISSING="" 	# Defines 2 arrays
	define -s tmp_pkg=""			# Defines a string
#
# Functions
#
	USAGE() {
	# Prints basic usage string
	# Please adjust as soon you know the options, if any.
		\$ECHO "\$SWARM_MSG_WORD_USAGE: \$ME [ \${SWARM_MSG_WORD_OPTIONS,,} ] [ \${SWARM_MSG_WORD_ARGUMENTS^^} ]"
	}
#
# Catch arguments
#
 	while :; do
 		case "\$1" in
 		""|-h|-\?|--help)
 			USAGE
 			exit 0
 			;;
 		--)
 			# General purpose pipe support, might need adjustment!
 			while read line;do
 				\$0 "\$line"
 			done
 			exit 0
 			;;
 		*)
 			break
 			;;
 		esac
 		shift
 	done
#
# Requirements
#
	REQ_CMD=(import other-cmd)
	for req in "\${REQ_CMD[@]}"
	do 	# Handle missing requirements
		if ! \$WHICH "\$req" >/dev/null
		then 	case "\$req" in
			import)
				case "\${BASED,,}" in
				# 'Exceptions'
				redhat)		tmp_pkg="ImageMagick"	;;
				debian)		tmp_pkg="imagemagick"	;;
				# Default handle,
				*)		tmp_pkg="ImageMagick"	;;
				;;
			# Base example to copy-paste
			*)
				case "\${BASED,,}"
				# Default handle
				*)		tmp_pkg="\$req"	;;
				esac
				;;
			esac
			REQ_MISSING+=(" \$tmp_pkg")
		fi
	done
	# Install missing packages
	[[ -n "\$REQ_MISSING" ]] && swam.os.install "\${REQ_MISSING[@]}"
#
# Action & Display
#
 	header --default #"\${@}"
 	title "Something"
 	printe "information"
 	exit \$RET
EO_SCREEN
