#!/usr/bin/env bash
#--------------------------------
script_version=0.1
ME=${0##*/}
script_name=${ME/.sh}
#--------------------------------
source SWARM/runtime

header --default
title yay
printe yes it works
