#!/usr/bin/env bash
# --------------------------------
# This script uses requires SWARM!
# When executing this file,
# you must have either the dir: "SWARM"
# or the file: "runtime" in your current directory
# --------------------------------
for d in . SWARM; do [[ -f "${d}/runtime" ]] && source ${d}/runtime && break ; done

header --default
title yay
printe yes it works
