#!/usr/bin/env bash
#
# SWARM theme file
#
#	header will use SWARM_COLOR_BG as background color,
#	and SWARM_COLOR_FG as font color.
#
#	'title' will use inverted colors
#
	SWARM_THEME_DATA[color-back]="red"
	SWARM_THEME_DATA[color-front]="white"
	#SWARM_THEME_DATA[color-back]=""
#
#	If 'border-right' is not set,
#	it will be inveresed from 'border_left'
#	border-color is not used for 'header'
#
	SWARM_THEME_DATA[border-left]="# |"
	#SWARM_THEME_DATA[border-right]=""
	#SWARM_THEME_DATA[border-color]=""
#
#	Char indicators / User prompt
#
#
	SWARM_THEME_DATA[read]="\076"
	SWARM_THEME_DATA[select]="${SWARM_THEME_DATA[read]}"
